spring.application.name: betterreads-data-loader
spring.main.allow-circular-references: true

datadump.location:
    author: C:\Users\akmap\Documents\ol_dump_authors_2022-11-30.txt
    works: C:\Users\akmap\Documents\ol_dump_works_2022-11-30.txt
spring:
    cassandra:
        keyspace-name: main
        username: <username>
        password: <password>
        schema-action: create-if-not-exists
        request:
            timeout: 10s
        connection:
            connect-timeout: 10s
            init-query-timeout: 10s

datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
    id: <id>
    region: asia-south1
    keyspace: main
    application.token:  <token>

                              







